name: travl-frontend
region: nyc

services:
  - name: web
    github:
      repo: ammarafridi-max/monorepo
      branch: master
      deploy_on_push: true
    source_dir: /
    dockerfile_path: apps/travl-frontend/Dockerfile
    http_port: 3000
    instance_count: 1
    instance_size_slug: basic-xxs
    envs:
      - key: NODE_ENV
        value: production
      - key: HOSTNAME
        value: "0.0.0.0"
      - key: PORT
        value: "3000"
