import { connectMongo, Order, QUEUE_NAMES, createRedisConnection } from '@travel-suite/picturesk-shared';
import { Queue } from 'bullmq';
const id = process.argv[2];
await connectMongo(process.env.MONGODB_URI);
const a = (await Order.findById(id).lean()).candidateScores?.length ?? 0;
process.stdout.write(`candidateScores t0=${a} `);
await new Promise(r=>setTimeout(r,15000));
const b = (await Order.findById(id).lean()).candidateScores?.length ?? 0;
console.log(`t+15s=${b}  => ${b>a?'PROGRESSING (+'+(b-a)+')':'FROZEN (no progress)'}`);
const conn = createRedisConnection(process.env.REDIS_URL);
const q = new Queue(QUEUE_NAMES.ORDER_PIPELINE, { connection: conn });
const active = await q.getJobs(['active']);
console.log('ACTIVE jobs:', active.map(j=>({orderId:j.data?.orderId, processedOn:j.processedOn?new Date(j.processedOn).toISOString():null})));
const failed = await q.getJobs(['failed']);
for (const j of failed) console.log('FAILED:', j.data?.orderId, '::', (j.failedReason||'').slice(0,180));
await q.close(); conn.disconnect(); process.exit(0);
